version: '3'

services:
 app:
   ports:
     - target: 80
       published: ${SERVER_PORT:-8888}
       protocol: tcp
       mode: host
   build: ./docker/app
   container_name: laravel_app
   volumes:
     - ./src:/var/www/html
 db:
   image: mysql:5.7
   container_name: laravel_db
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: laravel_db
     MYSQL_USER: laravel_user
     MYSQL_PASSWORD: laravel_pass
     TZ: 'Asia/Tokyo'
   command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
   volumes:
     - ./docker/db/data:/var/lib/mysql
     - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
   ports:
     - target: 3306
       published: ${DB_PORT:-3306}
       protocol: tcp
       mode: host
